version: "3"
services:
    server:
        image: danielkappelle/spotify-web-remote
        deploy:
            restart_policy:
                condition: on-failure
        env_file:
            - config.env
    client:
        image: danielkappelle/spotify-web-remote-client
        deploy:
            restart_policy:
                condition: on-failure
        ports:
            - "3002:80"
        links:
            - server
